--This file contains the data definition language (ddl) used to create all the project tables

CREATE TABLE IF NOT EXISTS public.abandoned_mines
(
    site_code varchar,
    wabmines_n varchar,
    feature_gr text,
    feature_ty text,
    site_type text,
    site_sub_t text,
    latitude numeric,
    longitude numeric,
    mga_zone integer,
    easting numeric,
    northing numeric,
    commoditie text,
    commodity_,
    target_com text,
    observatio date,
    originator text,
    bund text,
    bund_max numeric,
    bund_min numeric,
    condition text,
    visibility text,
    visual_imp,
    length numeric,
    width numeric,
    depth text,
    height numeric,
    strike numeric,
    azimuth numeric,
    dip numeric,
    edge_stabi text,
    base_condi text,
    excavation text,
    fences text,
    signs text,
    mf_shape text,
    revegetati text,
    ug_timbers text,
    ug_access text,
    headframe text,
    ug_seal_ty text,
    ug_seal_co text,
    open_cut_o text,
    water_cond text,
    ramp text,
    dump_mater text,
    dump_other text,
    dispersion text,
    dispersi00 numeric,
    site_confi text,
    point_conf text,
    web_link text,
    CONSTRAINT abandoned_mines_pkey PRIMARY KEY (site_code)
);




CREATE TABLE IF NOT EXISTS public.atlas_map
(
    project_code varchar,
    project_name text,
    site_code varchar,
    site_name text,
    site_short text,
    site_type text,
    site_subt text,
    site_stage text,
    site_com_g text,
    site_tcg text,
    confid text,
    latitude numeric,
    longitude numeric,
    mga_zone integer,
    easting numeric,
    northing numeric,
    mx_map text,
    atl_ml_n text,
    atl_ml_c text,
    atl_ml_ca text,
    atl_a_flag text
);




CREATE TABLE IF NOT EXISTS public.major_resource_projects
(
    site_code varchar,
    short_title text,
    title text,
    site_type text,
    sub_type text,
    stage text,
    project_code varchar,
    project_title text,
    longitude numeric,
    latitude numeric,
    easting numeric,
    northing numeric,
    mga_zone integer,
    commodities text,
    commodity_group_name text,
    target_group_name text,
    map_label_name text,
    include_commodity_flag text,
    map_commodities text,
    active_flag text,
    symbol text,
    symbol_status text,
    map_series text,
    confidentiality text,
    map_sheet_no_100k integer,
    map_sheet_name_100k text,
    map_sheet_no_250k text,
    map_sheet_name_250k text,
    lga_name text,
    development_region text,
    district_no integer,
    district_name text,
    tectonic_unit text,
    CONSTRAINT major_resource_projects_pkey PRIMARY KEY (site_code)
)
